// Auto-generated by didspace bindgen
// Host bindings for a WebAssembly Component (Wasmtime)

use wasmtime::component::bindgen;

bindgen!({
    path: "./wit",
    world: "hello",
});

// Tip: set WASMTIME_DEBUG_BINDGEN=1 to dump generated code if you debug compile errors.
